# Generated by Django 3.2.4 on 2021-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='service',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='support_animal',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
