# Generated by Django 3.2.4 on 2021-06-27 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petownergroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petcarelog',
            name='care_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.carecategory'),
        ),
        migrations.AddField(
            model_name='carecategory',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
