# Generated by Django 3.2.4 on 2021-09-27 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0003_auto_20210926_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(through='pet.PetOwnerGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
