# Generated by Django 3.2.4 on 2021-06-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='share_id',
            field=models.CharField(default='dvPqm0BWtiA6gyOqTCe9gwGf9KGptlxf01mcBrp0yLMYZSixSF', max_length=128, unique=True),
        ),
    ]
