# Generated by Django 3.2.4 on 2021-06-28 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
