# Generated by Django 3.2.4 on 2021-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_pet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='donate_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
