# Generated by Django 3.2.4 on 2021-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_auto_20210628_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecategory',
            name='input_type',
            field=models.IntegerField(blank=True, choices=[('text', 'テキスト'), ('integer', '整数'), ('integer', '小数点'), ('checkbox', 'チェックボックス')], null=True),
        ),
    ]
