# Generated by Django 3.2.4 on 2021-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_carecategory_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecategory',
            name='input_type',
            field=models.IntegerField(blank=True, choices=[('text', 'テキスト'), ('integer', '整数'), ('float', '小数点'), ('checkbox', 'チェックボックス')], null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('male', 'オス'), ('female', 'メス')], null=True),
        ),
    ]
