# Generated by Django 3.2.4 on 2021-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_auto_20210630_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecategory',
            name='input_type',
            field=models.CharField(blank=True, choices=[('text', 'テキスト'), ('integer', '整数'), ('float', '小数点'), ('checkbox', 'チェックボックス')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'オス'), ('female', 'メス')], max_length=16, null=True),
        ),
    ]
