# Generated by Django 3.2.4 on 2021-06-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_auto_20210630_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carecategory',
            name='pet',
        ),
    ]
