# Generated by Django 3.2.4 on 2021-06-29 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0010_remove_carecategory_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecategory',
            name='user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to='user.account'),
            preserve_default=False,
        ),
    ]
