# Generated by Django 3.2.4 on 2021-07-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_carecategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcarelog',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
