# Generated by Django 3.2.4 on 2021-07-01 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0012_petcarelog_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcarelog',
            name='user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='user.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
