# Generated by Django 3.2.4 on 2021-07-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_auto_20210701_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcarelog',
            name='pet',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
    ]
